version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # ✅ allow Jenkins to talk to Docker
    user: root  # ✅ allow installing packages like docker CLI
    restart: unless-stopped

volumes:
  jenkins_home: